-- Additive migration: real payment providers (NotchPay primary, Fapshi
-- fallback) sit behind the existing momo/orange payment_method values —
-- no new method is added. `provider` records which aggregator actually
-- processed a given attempt, since primary+fallback means either could
-- have. NULL means no aggregator involved (cod).
ALTER TABLE payments
  ADD COLUMN provider text CHECK (provider IN ('notchpay', 'fapshi')),
  ADD COLUMN provider_transaction_id text;

-- provider_ref is generated by us at charge-initiation time (a reliable
-- webhook-matching key even in a race where the webhook arrives before
-- our own initiating HTTP call returns) — unique so a duplicate/replayed
-- webhook can never land against the wrong row.
CREATE UNIQUE INDEX payments_provider_ref_unique_idx
  ON payments (provider_ref) WHERE provider_ref IS NOT NULL;
